// Code generated by go-bindata.
// sources:
// template/api.h
// template/api.m
// template/const
// template/model.h
// template/model.m
// DO NOT EDIT!

package cast

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _templateApiH = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x8c\x91\x41\x4f\xe3\x30\x10\x85\xcf\xf1\xaf\x18\x75\x2f\x71\xb4\xdb\xbd\x17\x84\x0a\x6d\x84\x08\xad\x8b\x48\x7b\xc8\x05\xcb\x4d\xa6\xd4\xd4\xb5\x2d\xdb\xa1\xaa\x10\xff\x1d\x45\x4a\x5a\x40\x41\xe2\xe6\x79\xef\x79\xbe\x67\xf9\x8f\xdc\x5b\xe3\x02\x5c\x66\xc5\x44\xf8\x70\x2f\xc3\xff\xd3\x69\xb8\xbd\x22\x9d\x3f\x78\x4b\xac\x70\x22\x79\x1f\x6e\x07\xfd\x22\x61\x39\xbf\xce\xf3\xd5\x3c\xe5\x6c\xc1\xd8\x6a\x36\xe3\x37\xe9\xed\x1d\x23\x64\x2c\x75\x40\xb7\x11\x25\x42\x56\xcc\x85\x95\x0c\xc3\xc1\xb8\xdd\x44\x49\xd4\x01\xe2\x6e\x0b\x25\xff\x20\xd6\xb5\x52\x62\xad\x10\x58\xbe\x7a\x9c\xe5\xe8\xbd\x34\x7a\x2a\x82\x58\x0a\xbf\x83\x84\xee\x85\x95\xbc\xbb\xc1\x0f\x32\x6c\xe7\xa6\xaa\x15\x2e\x8f\x16\x47\x71\x56\x9c\x27\x1a\x8e\x16\x49\x14\x35\xd1\xd1\x09\x02\x09\x70\xd6\x32\x68\x23\xed\x9b\x88\x33\xcf\x0e\xbd\x1f\x9d\xf1\xaf\x46\x56\x10\x3f\xd1\x98\xe5\x0f\xad\x0b\x09\x67\x46\x37\x09\x80\xda\x2a\x23\xaa\xce\xa1\xf4\xeb\x4c\xa2\xc8\xd7\x65\xf9\xe3\xc6\xbe\x97\x9d\x5a\x41\x10\x7e\xf7\x17\xfa\x0a\x83\x43\x6f\x8d\xf6\xb8\x58\xbf\x60\x19\x28\x6d\x29\x24\x8a\x36\x42\xaa\xda\xe1\xef\x79\xf0\x1d\x08\x90\x15\x0c\x43\xea\x9c\x71\x9f\xeb\x60\x23\x50\xda\x02\x2e\x08\x19\xa3\xae\xfa\xbe\x3b\x65\x53\xf2\x11\x00\x00\xff\xff\x93\xe2\xed\x0d\x50\x02\x00\x00")

func templateApiHBytes() ([]byte, error) {
	return bindataRead(
		_templateApiH,
		"template/api.h",
	)
}

func templateApiH() (*asset, error) {
	bytes, err := templateApiHBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "template/api.h", size: 592, mode: os.FileMode(420), modTime: time.Unix(1561011979, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _templateApiM = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x8c\x51\x5d\x6f\xda\x30\x14\x7d\x8e\x7f\xc5\x55\xf6\x12\x67\x1b\x3f\x20\x68\x12\x13\xdb\x0b\x1a\x59\xd5\xd0\x07\x84\x68\x64\x92\x4b\x71\x71\x6c\xeb\xda\x01\x21\xc4\x7f\xaf\x12\x25\xa1\x54\x54\x6a\x5e\x9c\xe3\xfb\x71\x8e\xcf\xf9\x26\x2b\x6b\xc8\x43\x38\x5b\xce\x85\x95\x29\xfa\xa3\xa1\xfd\x54\x49\xd4\xfe\xfb\x39\xb6\x82\x44\x7c\x19\xed\x42\xc6\xd8\x44\x56\x56\x61\x85\xda\x0b\x2f\x8d\x86\x3b\x13\x10\xf5\x23\x9c\xb1\x9f\x10\xe9\x5a\x29\xb1\x51\x08\x69\xf6\xf4\xf8\x2f\x43\xe7\xa4\xd1\x7f\x84\x17\x0b\xe1\xf6\x10\xf3\x4a\x58\x99\xf7\x23\xf9\x51\xfa\xdd\xdc\x94\xb5\xc2\xc5\xc9\x62\x12\xcd\x96\x57\xc4\xfd\xc9\x22\x0b\x82\xa6\x35\x19\x58\x20\x86\x3c\xed\x38\x78\x73\x55\x35\x2d\x64\x5e\x08\x9d\x4b\xae\xf4\x07\x23\x4b\x88\x9e\x79\x94\x66\x0f\x5d\x15\xe2\x3c\x35\xba\xe9\x00\xa8\xad\x32\xa2\xec\x2b\x9c\xdf\x62\x16\x04\xae\x2e\x8a\x4f\x37\xde\x7b\xd9\xa0\x0a\xbc\x70\xfb\x1f\x70\x4f\x30\x10\x3a\x6b\xb4\xc3\xff\x9b\x57\x2c\x3c\xe7\x1d\x0b\x0b\x82\xad\x90\xaa\x26\xfc\x3a\x1f\x7c\x24\x04\x98\x2d\x53\xf4\x7f\x89\x0c\xbd\x97\x83\xcd\x05\xe7\x1d\xc1\x99\xb5\x86\x56\x23\x51\xb4\x91\xfe\x82\x49\xd8\x4b\x0d\xc7\x2c\x20\xf4\x35\x69\x58\x39\x54\x5b\x68\xc3\xb2\xc6\xf9\xa4\xc3\x6d\x38\xbf\xad\xcc\x90\x0e\x48\x49\x93\xd0\x1a\xda\x7d\xe8\x91\x5c\xd2\xfe\x02\xa1\x9d\x2a\xe1\x5c\xb2\x1a\x4c\x28\x1a\xbc\x86\x21\xa8\x5b\xbf\xa1\x77\xbb\x3b\xa1\x77\xa3\x3b\xd7\x63\x76\x61\x6c\x82\xba\x64\xed\xf7\x16\x00\x00\xff\xff\x6c\x74\x07\x41\xc3\x02\x00\x00")

func templateApiMBytes() ([]byte, error) {
	return bindataRead(
		_templateApiM,
		"template/api.m",
	)
}

func templateApiM() (*asset, error) {
	bytes, err := templateApiMBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "template/api.m", size: 707, mode: os.FileMode(420), modTime: time.Unix(1561013752, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _templateConst = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xf2\x8a\x0c\x4a\x2d\x2e\xc8\xcf\x2b\x4e\xf5\xcd\x4f\x49\xcd\xd1\xf1\x8a\x0c\x2c\x4d\x2d\xaa\x0c\x48\x2c\x4a\xcc\x4d\x2d\x49\x2d\xd2\xf1\x8a\xf4\x4d\x2c\xc8\xf4\x4b\x2d\x29\xcf\x2f\xca\x76\xce\xc9\x4c\xcd\x2b\x01\x04\x00\x00\xff\xff\x94\xcb\x8f\x64\x34\x00\x00\x00")

func templateConstBytes() ([]byte, error) {
	return bindataRead(
		_templateConst,
		"template/const",
	)
}

func templateConst() (*asset, error) {
	bytes, err := templateConstBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "template/const", size: 52, mode: os.FileMode(420), modTime: time.Unix(1561012612, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _templateModelH = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x52\xce\xcc\x2d\xc8\x2f\x2a\x51\xb0\xf1\x8a\x74\x4e\x2c\x2e\xf1\xce\x2c\xd1\x87\xb3\xf4\x32\xec\xb8\xb8\xaa\xb5\x0a\x12\x8b\x12\xb5\x6a\xb9\xb8\xfc\x82\xe3\x1d\x83\x83\x43\x7d\x5d\xe3\xfd\xfc\xfd\xfc\x42\x7d\x7c\xe2\x9d\x5c\xdd\x3d\xfd\xb8\xb8\x1c\x32\xf3\x4a\x52\x8b\xd2\x12\x93\x53\x15\x60\xaa\xad\xe0\xda\xe0\x0c\x87\xd4\xbc\x14\x6c\x86\xb8\xfa\xb9\x70\x71\x71\x71\x01\x02\x00\x00\xff\xff\xb0\x4c\x13\xa4\x89\x00\x00\x00")

func templateModelHBytes() ([]byte, error) {
	return bindataRead(
		_templateModelH,
		"template/model.h",
	)
}

func templateModelH() (*asset, error) {
	bytes, err := templateModelHBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "template/model.h", size: 137, mode: os.FileMode(420), modTime: time.Unix(1561006625, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _templateModelM = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x3c\xcd\x4d\x0a\xc2\x40\x0c\xc5\xf1\x75\x73\x8a\x50\x37\x5a\xa1\x3d\x80\x9b\x42\x05\x77\x22\x78\x82\xd8\x06\x3a\x30\x93\x0c\x69\x2a\x94\xd2\xbb\x8b\xf8\xb1\x7b\xbc\xdf\xe2\xbf\x0b\x29\xab\x39\x96\x6b\x95\xc9\xa8\xda\xea\xb1\x04\x68\x43\xca\x91\x13\x8b\x93\x07\x15\xfc\x21\xc0\x11\xf7\xd7\xfb\x39\xf4\xef\x9b\x6c\xc1\xea\x90\x74\xe0\xd8\xa9\x38\x05\x61\xbb\x99\x66\x36\x5f\x2e\x2c\x6c\xa1\xef\x22\x4d\x13\xae\x50\x34\x0d\x3e\x29\xce\x8c\xd3\xa8\x73\x1c\xf0\xc1\xf8\x31\xb5\xef\x10\x4a\x5c\x43\x61\xec\xb3\x09\xb6\xeb\xbf\x59\x6c\x27\xd8\x00\x5a\x96\xe1\x15\x00\x00\xff\xff\x51\x9f\x74\x49\xae\x00\x00\x00")

func templateModelMBytes() ([]byte, error) {
	return bindataRead(
		_templateModelM,
		"template/model.m",
	)
}

func templateModelM() (*asset, error) {
	bytes, err := templateModelMBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "template/model.m", size: 174, mode: os.FileMode(420), modTime: time.Unix(1561009961, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"template/api.h":   templateApiH,
	"template/api.m":   templateApiM,
	"template/const":   templateConst,
	"template/model.h": templateModelH,
	"template/model.m": templateModelM,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"template": &bintree{nil, map[string]*bintree{
		"api.h":   &bintree{templateApiH, map[string]*bintree{}},
		"api.m":   &bintree{templateApiM, map[string]*bintree{}},
		"const":   &bintree{templateConst, map[string]*bintree{}},
		"model.h": &bintree{templateModelH, map[string]*bintree{}},
		"model.m": &bintree{templateModelM, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
